"""add username

Revision ID: 94a1cb8c58a0
Revises: e3f9c9560083
Create Date: 2026-03-28 14:23:10.271082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a1cb8c58a0'
down_revision: Union[str, Sequence[str], None] = 'e3f9c9560083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        
    op.execute("UPDATE users SET username = substr(email, 1, instr(email, '@') - 1)")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
